### ISSUE TITLE
Cannot work with NA values

### ISSUE THREAD

**Issue by stas-brain** [Manuelfjr/birt-gd#5]
Hello,
The repo assumes that the input data has no NA values. I need to train a model with input data which contains NA values (where a user did not answer a question).
In my particular case, I have ~150 items, answered by ~10000 people, each of whom answered ~20 items each. So most of my input data is NA values.

**Comment by stas-brain** [comment]
I managed to fix this on my end.

**Comment by Manuelfjr** [comment]
> I managed to fix this on my end.

Hi,
Glad you were able to resolve it. We are working on tweaking the model to support receiving missing data in its response matrix for future releases. Thanks for your question.
